###
GET http://localhost:9999/customers/23 HTTP/1.1

###
GET http://localhost:9999/customers HTTP/1.1
Authorization: Basic a:1

###
POST  http://localhost:9999/customers HTTP/1.1
Authorization: Basic a:1


###
DELETE  http://localhost:9999/customers/44 HTTP/1.1

###
POST http://localhost:9999/customers/42/block HTTP/1.1
Authorization: Basic a:1

###
DELETE  http://localhost:9999/customers/42/block HTTP/1.1
Authorization: Basic a:1